network:
  ethernets:
    SECONDARY_IFACE:
      addresses:
        - SECONDARY_CIDR
      nameservers:
        addresses: [1.1.1.1, 1.0.0.1]
      routes:
        - to: default
          via: SECONDARY_GATEWAY
          table: 200
      routing-policy:
        - from: 0.0.0.0/0
          table: 254 # main table
          priority: 100
          mark: 100 # ipset mark : 0x64
        - from: SECONDARY_IP
          table: 200
          priority: 200
          mark: 524288 # tailscale exit mark : 0x80000
    PRIMARY_IFACE:
      addresses:
        - PRIMARY_CIDR
      nameservers:
        addresses: [1.1.1.1, 1.0.0.1]
      routes:
        - to: default
          via: PRIMARY_GATEWAY
