network:
  ethernets:
    PUBLIC_IFACE:
      addresses:
        - PUBLIC_CIDR
      nameservers:
        addresses: [1.1.1.1, 1.0.0.1]
      routes:
        - to: default
          via: PUBLIC_GATEWAY
      routing-policy:
        - from: 0.0.0.0/0
          table: 254 # main table
          priority: 100
          mark: 100 # ipset mark : 0x64
    PRIVATE_IFACE:
      addresses:
        - PRIVATE_CIDR
